name: dmp_env
channels:
  - defaults
dependencies:
  - aom=3.12.1=ha237518_0
  - attrs=25.4.0=py311hca03da5_2
  - blas=1.0=openblas
  - blosc=1.21.6=h7977b18_0
  - branca=0.8.1=py311hca03da5_1
  - brotlicffi=1.2.0.0=py311h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hfe05a68_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - certifi=2026.01.04=py311hca03da5_0
  - cffi=2.0.0=py311h73c2a22_1
  - charset-normalizer=3.4.4=py311hca03da5_0
  - click=8.1.8=py311hca03da5_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - contourpy=1.3.3=py311h20e30b6_0
  - cycler=0.12.1=py311hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.4=h50f4ffc_0
  - fiona=1.10.1=py311h50f4ffc_2
  - folium=0.20.0=py311hca03da5_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.61.0=py311haa24f5a_0
  - freetype=2.14.1=h7cdc921_0
  - freexl=2.0.0=ha3de405_0
  - fribidi=1.0.16=h8859324_0
  - geopandas=1.1.1=py311hca03da5_1
  - geopandas-base=1.1.1=py311hca03da5_1
  - geos=3.10.6=h313beb8_0
  - geotiff=1.7.4=h9ba101e_0
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=12.3.0=h9837a22_1
  - icu=73.1=h313beb8_0
  - idna=3.11=py311hca03da5_0
  - jansson=2.14=h80987f9_1
  - jinja2=3.1.6=py311hca03da5_0
  - joblib=1.5.3=py311hca03da5_0
  - jpeg=9f=h2f69dba_0
  - json-c=0.18=h254cc4a_0
  - kiwisolver=1.4.9=py311haeee614_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libarchive=3.8.2=ha845c4f_0
  - libavif=1.3.0=h839b4eb_0
  - libbrotlicommon=1.2.0=hbd7815e_0
  - libbrotlidec=1.2.0=h1e834b2_0
  - libbrotlienc=1.2.0=h5439a07_0
  - libcurl=8.18.0=hd4c70c6_0
  - libcxx=21.1.8=hb4ce287_0
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libgdal-core=3.11.4=hef1d0ff_1
  - libgfortran=15.2.0=h09d7db9_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.86.3=hcacd345_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libkml=1.3.0=hc4d7c42_7
  - libkrb5=1.22.1=ha46c28b_0
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.31=h7813bb4_0
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.54=h5c318fc_0
  - libspatialite=5.1.0=hfc41e38_3
  - libssh2=1.11.1=h3e2b118_0
  - libtiff=4.7.1=h367c460_0
  - libunistring=1.3=h1799b2a_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxcb=1.17.0=h3fc13f7_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lmdb=0.9.31=h79febb2_0
  - lz4-c=1.9.4=h313beb8_1
  - mapclassify=2.10.0=py311hca03da5_1
  - markupsafe=3.0.2=py311h80987f9_0
  - matplotlib-base=3.10.8=py311haa222d5_0
  - minizip=4.0.3=ha89c15f_0
  - ncurses=6.5=hee39554_0
  - networkx=3.6.1=py311hca03da5_0
  - numpy=2.4.2=py311h4bb6f22_0
  - numpy-base=2.4.2=py311h23175f9_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py311hca03da5_1
  - pandas=3.0.0=py311h3f644e9_0
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.1.0=py311h7b5562e_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - proj=9.7.1=hea583f4_0
  - pthread-stubs=0.3=h1a28f6b_1
  - pycparser=2.23=py311hca03da5_0
  - pyogrio=0.10.0=py311h3647eba_1
  - pyparsing=3.2.5=py311hca03da5_0
  - pyproj=3.7.2=py311h50288c5_0
  - pysocks=1.7.1=py311hca03da5_1
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py311hca03da5_1
  - scikit-learn=1.8.0=py311h003a250_0
  - scipy=1.16.3=py311h08a1045_0
  - setuptools=80.10.2=py311hca03da5_0
  - shapely=2.1.2=py311h72d6987_0
  - six=1.17.0=py311hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - threadpoolctl=3.5.0=py311h7eb115d_1
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - uriparser=0.9.8=h2942776_0
  - urllib3=2.6.3=py311hca03da5_0
  - wheel=0.46.3=py311hca03da5_0
  - xerces-c=3.3.0=h94d498e_0
  - xorg-libxau=1.0.12=h3fc13f7_0
  - xorg-libxdmcp=1.1.5=h3fc13f7_0
  - xyzservices=2025.4.0=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
